export const TEST_VALUE = 'TEST_VALUE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';

export const PRODUCT_DETAILS = 'PRODUCT_LIST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_LIST_FAILURE';

export const PROFILE = 'PROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILES_FAILURE = 'PROFILES_FAILURE';

export const SEARCH = 'PROFILE';
export const SEARCH_SUCCESS = 'PROFILE_SUCCESS';
export const  SEARCH_FAILURE = 'PROFILES_FAILURE';

export const DELETE = 'PROFILE';
export const DELETE_SUCCESS = 'PROFILE_SUCCESS';
export const  DELETE_FAILURE = 'PROFILES_FAILURE';